### ISSUE TITLE
'meta_as_tags' hasn't been updated in READMEs

### ISSUE THREAD

**Issue by agemuend** [ClusterCockpit/cc-metric-collector#90]
Since #63 meta_as_tags expects a list instead of a boolean. Unfortunately this hasn't been updated in the READMEs, e.g. https://github.com/ClusterCockpit/cc-metric-collector/blob/main/sinks/README.md and https://github.com/ClusterCockpit/cc-metric-collector/blob/main/sinks/httpSink.md

With the examples in these READMEs you'll receive an unhelpful Go error (cannot unmarshal bool into go struct field). It would be nice if it would output the line in the JSON where the error occured btw.

**Comment by TomTheBear** [comment]
Thanks for the report. Fixed in https://github.com/ClusterCockpit/cc-metric-collector/commit/0f35469168ac16fdfada59c23fb11861c61595bc and https://github.com/ClusterCockpit/cc-metric-collector/commit/f0da07310b01898f476ca7502aed81f2cd0c236e

I'll check whether there is way to get more detailed information out of the JSON parser in case of error.
